#!/usr/bin/env python3
"""Maintainers only: assemble asm/cave.s into src/fm_multi_drop/cave_data.py.

Needs the MIPS GNU binutils (Debian/Ubuntu: apt install binutils-mips-linux-gnu).
End users never need this: the assembled bytes are committed in cave_data.py.
"""
import hashlib, os, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAVE_ADDR, LOOP_ENTRY, PAD = 0x801db038, 0x801db03c, 8


def assemble() -> bytes:
    src, ld = os.path.join(ROOT, "asm", "cave.s"), os.path.join(ROOT, "asm", "cave.ld")
    with tempfile.TemporaryDirectory() as t:
        o, elf, out = (os.path.join(t, x) for x in ("c.o", "c.elf", "c.bin"))
        subprocess.check_call(["mips-linux-gnu-as", "-EL", "-mips1", "-o", o, src])
        subprocess.run(["mips-linux-gnu-ld", "-EL", "-T", ld, "-e", "loop_entry", "-o", elf, o],
                       check=True, stderr=subprocess.DEVNULL)
        syms = subprocess.check_output(["mips-linux-gnu-nm", elf], text=True)
        addr = {l.split()[2]: int(l.split()[0], 16) for l in syms.splitlines() if len(l.split()) == 3}
        subprocess.check_call(["mips-linux-gnu-objcopy", "-O", "binary", "--only-section=.text", elf, out])
        with open(out, "rb") as f:
            raw = f.read()
    cave = bytearray(raw[PAD:])  # linker aligns .text to 16 bytes; drop the padding
    assert addr["n_value"] == CAVE_ADDR and addr["loop_entry"] == LOOP_ENTRY, addr
    cave[0] = 0  # first byte is the drop count N, filled in when patching
    return bytes(cave)


def main() -> None:
    cave = assemble()
    lines = [cave.hex()[i:i + 64] for i in range(0, len(cave.hex()), 64)]
    body = "\n".join(f'    "{l}"' for l in lines)
    text = (f'"""GENERATED by tools/build_cave.py from asm/cave.s -- do not edit by hand."""\n'
            f"CAVE = bytes.fromhex(\n{body}\n)\n"
            f'CAVE_SHA256 = "{hashlib.sha256(cave).hexdigest()}"\n')
    dest = os.path.join(ROOT, "src", "fm_multi_drop", "cave_data.py")
    with open(dest, "w") as f:
        f.write(text)
    print(f"wrote {dest} ({len(cave)} bytes, sha256 {hashlib.sha256(cave).hexdigest()[:16]}...)")


if __name__ == "__main__":
    sys.exit(main())
